### ISSUE TITLE
Bug found while setup

### ISSUE THREAD

**Issue by guizhenwei** [pybee/liquid-demo#3]
```
(venv) MacPros-iMac:liquid-demo mac$ python setup.py macos
running macos
 * Writing application template...
Project template: https://github.com/pybee/Python-macOS-template.git
Traceback (most recent call last):
  File "/Users/mac/.code/liquid/venv/lib/python3.6/site-packages/cookiecutter/vcs.py", line 129, in clone
    stderr=subprocess.STDOUT,
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'checkout', '3.6']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    'icon': 'icons/macos',
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/mac/.code/liquid/venv/lib/python3.6/site-packages/briefcase/app.py", line 255, in run
    self.generate_app_template()
  File "/Users/mac/.code/liquid/venv/lib/python3.6/site-packages/briefcase/app.py", line 170, in generate_app_template
    'secret_key': self.secret_key,
  File "/Users/mac/.code/liquid/venv/lib/python3.6/site-packages/cookiecutter/main.py", line 63, in cookiecutter
    no_input=no_input,
  File "/Users/mac/.code/liquid/venv/lib/python3.6/site-packages/cookiecutter/repository.py", line 84, in determine_repo_dir
    no_input=no_input,
  File "/Users/mac/.code/liquid/venv/lib/python3.6/site-packages/cookiecutter/vcs.py", line 132, in clone
    if 'not found' in clone_error.output.lower():
TypeError: a bytes-like object is required, not 'str'
(venv) MacPros-iMac:liquid-demo mac$
```

**Comment by freakboy3742** [comment]
This appears to be an issue with support for Python 3.6. There isn't currently a macOS template for Python 3.6, and the error condition isn't very helpful.
